[font]
size = 12

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[scrolling]
history = 100_000

[window]
option_as_alt = "OnlyRight" # Use right option key as alt, left option key as meta (for #€é etc.) [set to "Both" to use both as alt]

[general]
import = [
  "/Users/mia/.config/alacritty/dark.toml"
]
